defaultNamespace: gorizond

helm:
  values:
    env:
      - name: YOOKASSA_SHOP_ID
        value: "${ if hasKey .ClusterAnnotations 'gorizond.yookassa.id' }${ get .ClusterAnnotations 'gorizond.yookassa.id' }${ else }ID${ end }"
      - name: YOOKASSA_SECRET_KEY
        value: ${ if hasKey .ClusterAnnotations "gorizond.yookassa.key" }${ get .ClusterAnnotations "gorizond.yookassa.key" }${ else }KEY${ end }
    ingress:
      issuerMail: ${ if hasKey .ClusterAnnotations "cloudflare-email" }${ get .ClusterAnnotations "cloudflare-email" }${ else }admin@gorizond.io${ end }
      annotations:
        kubernetes.io/tls-acme: 'true'
      tls: 
        - hosts:
          - '${ if hasKey .ClusterAnnotations "gorizond.domain.pay" }${ get .ClusterAnnotations "gorizond.domain.pay" }${ else }gorizond.cluster${ end }'
          secretName: gorizond-pay-tls
      hosts:
        - host: ${ if hasKey .ClusterAnnotations "gorizond.domain.pay" }${ get .ClusterAnnotations "gorizond.domain.pay" }${ else }gorizond.cluster${ end }
          paths:
            - path: /
              pathType: ImplementationSpecific
      